### ISSUE TITLE
Backwards compatibility with 3.1.2?

### ISSUE THREAD

**Issue by ctgraham** [ewhanson/authorRequirements#5] opened 2020-06-29 14:30 UTC
The README for v.1.0.0-1 removes reference to 3.1.2, but the diff doesn't suggest breaking changes.  Is the intent for v1.0.0-1 still to be compatible with 3.1.2?

https://github.com/ewhanson/authorRequirements/compare/v1.0.0-0...v1.0.0-1

**Comment by ewhanson** [comment] 2020-07-03 22:51
Hi @ctgraham, the change to v1.0.0-1 addressed the addition of `publicationId` in 3.2.0. I did test it out and it seems to still work, but it was intended to be a fix for that change 3.2.0 only and not necessarily have backwards compatibility with 3.1.2. Perhaps the versioning makes this less clear than it should be. My intention is to maintain a 3.2.x and 3.1.2 version of the plugin. I'll clear that ambiguity up.

**Comment by ctgraham** [comment] 2020-07-06 13:35
My curiosity began with the report in the Plugin Gallery for OJS 3.1.2 that there was an upgrade available for v1.0.0.0.

I think this is because https://pkp.sfu.ca/ojs/xml/plugins.xml formats the `version` with a dash on the release, rather than a dot:
```
<release date="2019-10-27" version="1.0.0-0" md5="0303e950caf99d2c4a9d11529ddb18db">
```

So, when running 1.0.0.0, the Plugin Gallery incorrectly reports an upgrade available.  @asmecher should be able to correct the plugins.xml file.

**Comment by asmecher** [comment] 2020-07-07 22:08
@ctgraham, I've corrected the typo in `plugins.xml` -- does that resolve the issue?

**Comment by ctgraham** [comment] 2020-07-07 22:11
Yes, @asmecher , in the Plugin Gallery for 3.2.1, version 1.0.0.0 of the plugin now reports as "Up to date".

**Comment by asmecher** [comment] 2020-07-07 22:16
Great! I don't have permissions to close this issue, so I'll leave it to @ewhanson.

**Comment by ewhanson** [comment] 2020-07-07 22:18
Thanks @ctgraham and @asmecher!

**Closed by ewhanson** 2020-07-07 22:18 UTC
